name: Compile blueprint

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_blueprint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install system dependencies
        run: sudo apt-get install -y graphviz libgraphviz-dev

      - name: Install leanblueprint
        run: pip install leanblueprint

      - name: Compile blueprint
        run: mkdir -p blueprint/web && cd blueprint/src && plastex -c plastex.cfg web.tex

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: blueprint/web

  deploy:
    needs: build_blueprint
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
